import { Toaster } from "sonner";
import "./../styles/globals.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader/>
        {children}
        <Toaster/>  
      </body>
    </html>
  );
}
